server:
  port: 0 # random port

spring:
  application:
    name: account-management-service
  rabbitmq:
    host: localhost
    port: 5672
    usename: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}