version: '3.5'

services:
  user_db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user1
    ports:
      - 5432:5432
    volumes:
      - ./volumes/userdb:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
    - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  elasticsearch:
    image: elasticsearch:7.9.3
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash:7.9.3
    hostname: logstash
    ports:
      - 9600:9600
      - 8089:8089
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.3
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
