version: '3'

services:

  user_db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user1
    ports:
      - 5432:5432
    volumes:
      - ./volumes/userdb:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
    - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
