server:
  port: 8000

spring:
  application:
    name: eureka-discovery-service
  security:
    user:
      name: eureka
      password: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka