version: '3'

services:
  user_db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user1
    ports:
      - 5432:5432
    volumes:
      - ./volume:/var/lib/postgresql/data